using MockUsers.Validation;
using System.ComponentModel.DataAnnotations;

namespace MockUsers.DTO
{
    // In a creation class we assume all the fields are required excepts the id is auto generated by the factory
    public class NewStaticUserDTO
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Name Required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Email Required")]
        [EmailAddress(ErrorMessage = "Invalid Email Format")]
        public string  Email{ get; set; }
        [Required(ErrorMessage = "Gender Required")]
        [GenderValidation]
        public string Gender { get; set; }
        [Required(ErrorMessage = "Phone Required")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Country Required")]
        public string Country { get; set; }

    }
}
